### PR TITLE
Fixed the navbar to the top and reduced video size to 200kb

### PR DESCRIPTION
**Pull request by initishh**
Also,
1. Fonts changed into Roboto except that of navbar.
2. Text properly aligned for small screens.

ezgif com-video-to-gif (1)

### CODE REVIEW

**Comment by ankitjena** [comment]
The 'WONDER THINK CREATE' goes below screen. For larger screen it should be like
Screenshot from 2019-05-01 11-47-37

And for smaller screens
Screenshot from 2019-05-01 11-50-09

Use media queries.
Look at [https://github.com/contra/react-responsive](https://github.com/contra/react-responsive) or [material ui media query(unstable)](https://material-ui.com/layout/use-media-query/)

**Comment by initishh** [comment]
#47 #39 #45 issues solved.
 Above problem was also fixed.
ezgif com-video-to-gif

**Comment by ankitjena** [comment]
@initishh Good Work. The font is still montserrat in first introduction and what we do. Change it to Roboto and we will merge.

**Comment by initishh** [comment]
Font changed to Roboto.

**Pull request merged**
