### PR TITLE
card component added in place of paper 

### PR DESCRIPTION
**Pull request by harisumaid**
unequal height issue fixed but facing problem while making the Link tag stick to the bottom

### CODE REVIEW

**Comment by ganeshpatro321** [comment]
Provide a screenshot, screencasting is preferable showing the page in different sizes. @harisumaid

**Comment by harisumaid** [comment]
Screenshot from 2019-04-30 10-38-28
Screenshot from 2019-04-30 10-38-42
Screenshot from 2019-04-30 10-38-53

**Comment by ganeshpatro321** [comment]
Looks good, we still need to standardize the heights of the inner divs of the card.

**Comment by aquibbaig** [comment]
Use a proper layout of text inside the card. Like every text-heading should span two lines high and so on

**Pull request merged**
