### PR TITLE
Timeline implemented

### PR DESCRIPTION
**Pull request by mahesdwivedi**
Designed the timeline. Metadata required.

timeline

### CODE REVIEW

**Comment by ankitjena** [comment]
@mahesdwivedi Change the background and font to "Roboto"

**Comment by aquibbaig** [comment]
I didn't follow the discussion. What do we want to achieve through this timeline?

**Comment by aquibbaig** [comment]
Another thing: match your color scheme with that of the exisiting website

**Comment by mahesdwivedi** [comment]
how about this shade @aquibbaig  @ankitjena 
timeline

**Comment by ankitjena** [comment]
Go with something that looks good overall. It just seems like you have
changed the color. Font adjustments also needed.

**Comment by aquibbaig** [comment]
@mahesdwivedi First update your remote to the latest changes

**Comment by aquibbaig** [comment]
@mahesdwivedi Replace the last icon of the timeline to something else

**Comment by aquibbaig** [comment]
This looks good. Will be merged tomorrow!

**Comment by mahesdwivedi** [comment]
@ankitjena , I was refering to the color only at that time

**Comment by mahesdwivedi** [comment]
@aquibbaig i couldnt find anything else that would go well as the last icon other than the star.

**Comment by mahesdwivedi** [comment]
Changed Color, Icon and font
timeline2

**Comment by agathver** [comment]
Why close this?

**Comment by aquibbaig** [comment]
I did it by chance from his system

**Pull request closed without merging**
